ALTER TABLE assets ADD COLUMN IF NOT EXISTS nationality TEXT;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS role TEXT;

-- Clear old seed data; CASCADE wipes dependent rows in orders, trades, positions
TRUNCATE assets CASCADE;

INSERT INTO assets (id, symbol, name, description, nationality, role) VALUES
-- India - Batsman
(gen_random_uuid(), 'GAIKWAD',    'Ruturaj Gaikwad',       '', 'India', 'Batsman'),
(gen_random_uuid(), 'RASHEED',    'Shaik Rasheed',          '', 'India', 'Batsman'),
(gen_random_uuid(), 'VARMA',      'Tilak Varma',            '', 'India', 'Batsman'),
(gen_random_uuid(), 'TRIPATHI',   'Rahul Tripathi',         '', 'India', 'Batsman'),
(gen_random_uuid(), 'DHIR',       'Naman Dhir',             '', 'India', 'Batsman'),
(gen_random_uuid(), 'KOHLI',      'Virat Kohli',            '', 'India', 'Batsman'),
(gen_random_uuid(), 'PATIDAR',    'Rajat Patidar',          '', 'India', 'Batsman'),
(gen_random_uuid(), 'CHHIKARA',   'Swastik Chhikara',       '', 'India', 'Batsman'),
(gen_random_uuid(), 'SHAW',       'Prithvi Shaw',           '', 'India', 'Batsman'),
(gen_random_uuid(), 'RAGHUVANSH', 'Angkrish Raghuvanshi',   '', 'India', 'Batsman'),
(gen_random_uuid(), 'MPANDEY',    'Manish Pandey',          '', 'India', 'Batsman'),
(gen_random_uuid(), 'PADIKKAL',   'Devdutt Padikkal',       '', 'India', 'Batsman'),
(gen_random_uuid(), 'MANOHAR',    'Abhinav Manohar',        '', 'India', 'Batsman'),
(gen_random_uuid(), 'VERMA',      'Aniket Verma',           '', 'India', 'Batsman'),
(gen_random_uuid(), 'RAHANE',     'Ajinkya Rahane',         '', 'India', 'Batsman'),
(gen_random_uuid(), 'ASSHARMA',   'Ashutosh Sharma',        '', 'India', 'Batsman'),
(gen_random_uuid(), 'NAIR',       'Karun Nair',             '', 'India', 'Batsman'),
(gen_random_uuid(), 'IYER',       'Shreyas Iyer',           '', 'India', 'Batsman'),
(gen_random_uuid(), 'WADHERA',    'Nehal Wadhera',          '', 'India', 'Batsman'),
(gen_random_uuid(), 'ARYA',       'Priyansh Arya',          '', 'India', 'Batsman'),
(gen_random_uuid(), 'AGARWAL',    'Mayank Agarwal',         '', 'India', 'Batsman'),
(gen_random_uuid(), 'GILL',       'Shubman Gill',           '', 'India', 'Batsman'),
(gen_random_uuid(), 'SHKHAN',     'Shahrukh Khan',          '', 'India', 'Batsman'),
(gen_random_uuid(), 'PYADAV',     'Prince Yadav',           '', 'India', 'Batsman'),
(gen_random_uuid(), 'KULKARNI',   'Arshin Kulkarni',        '', 'India', 'Batsman'),
(gen_random_uuid(), 'JAISWAL',    'Yashasvi Jaiswal',       '', 'India', 'Batsman'),
(gen_random_uuid(), 'SURYAVANSH', 'Vaibhav Suryavanshi',   '', 'India', 'Batsman'),
(gen_random_uuid(), 'SHSINGH',    'Shashank Singh',         '', 'India', 'Batsman'),
(gen_random_uuid(), 'DUBEY',      'Shubham Dubey',          '', 'India', 'Batsman'),
-- India - Bowler
(gen_random_uuid(), 'DCHAHAR',    'Deepak Chahar',          '', 'India', 'Bowler'),
(gen_random_uuid(), 'KAHMED',     'Khaleel Ahmed',          '', 'India', 'Bowler'),
(gen_random_uuid(), 'KAMBOJ',     'Anshul Kamboj',          '', 'India', 'Bowler'),
(gen_random_uuid(), 'CHOUDHARY',  'Mukesh Choudhary',       '', 'India', 'Bowler'),
(gen_random_uuid(), 'BUMRAH',     'Jasprit Bumrah',         '', 'India', 'Bowler'),
(gen_random_uuid(), 'KSHARMA',    'Karn Sharma',            '', 'India', 'Bowler'),
(gen_random_uuid(), 'AKUMAR',     'Ashwani Kumar',          '', 'India', 'Bowler'),
(gen_random_uuid(), 'SIRAJ',      'Mohammad Siraj',         '', 'India', 'Bowler'),
(gen_random_uuid(), 'PUTHUR',     'Vignesh Puthur',         '', 'India', 'Bowler'),
(gen_random_uuid(), 'BISHNOI',    'Ravi Bishnoi',           '', 'India', 'Bowler'),
(gen_random_uuid(), 'DAR',        'Rasikh Dar',             '', 'India', 'Bowler'),
(gen_random_uuid(), 'BKUMAR',     'Bhuvneshwar Kumar',      '', 'India', 'Bowler'),
(gen_random_uuid(), 'MALIK',      'Umran Malik',            '', 'India', 'Bowler'),
(gen_random_uuid(), 'DESHPANDE',  'Tushar Deshpande',       '', 'India', 'Bowler'),
(gen_random_uuid(), 'CHAKVART',   'Varun Chakaravarthy',    '', 'India', 'Bowler'),
(gen_random_uuid(), 'MKHAN',      'Mohsin Khan',            '', 'India', 'Bowler'),
(gen_random_uuid(), 'MARKANDE',   'Mayank Markande',        '', 'India', 'Bowler'),
(gen_random_uuid(), 'SAKARIYA',   'Chetan Sakariya',        '', 'India', 'Bowler'),
(gen_random_uuid(), 'ARORA',      'Vaibhav Arora',          '', 'India', 'Bowler'),
(gen_random_uuid(), 'SHAMI',      'Mohammed Shami',         '', 'India', 'Bowler'),
(gen_random_uuid(), 'CHAHAL',     'Yuzvendra Chahal',       '', 'India', 'Bowler'),
(gen_random_uuid(), 'RCHAHAR',    'Rahul Chahar',           '', 'India', 'Bowler'),
(gen_random_uuid(), 'SMSINGH',    'Simarjeet Singh',        '', 'India', 'Bowler'),
(gen_random_uuid(), 'ANSARI',     'Zeeshan Ansari',         '', 'India', 'Bowler'),
(gen_random_uuid(), 'KYADAV',     'Kuldeep Yadav',          '', 'India', 'Bowler'),
(gen_random_uuid(), 'NATARAJAN',  'T. Natarajan',           '', 'India', 'Bowler'),
(gen_random_uuid(), 'KRISHNA',    'Prasidh Krishna',        '', 'India', 'Bowler'),
(gen_random_uuid(), 'MKUMAR',     'Mukesh Kumar',           '', 'India', 'Bowler'),
(gen_random_uuid(), 'SDSHARMA',   'Sandeep Sharma',         '', 'India', 'Bowler'),
(gen_random_uuid(), 'ARSINGH',    'Arshdeep Singh',         '', 'India', 'Bowler'),
(gen_random_uuid(), 'AVKHAN',     'Avesh Khan',             '', 'India', 'Bowler'),
(gen_random_uuid(), 'YTHAKUR',    'Yash Thakur',            '', 'India', 'Bowler'),
(gen_random_uuid(), 'KISHORE',    'Sai Kishore',            '', 'India', 'Bowler'),
(gen_random_uuid(), 'HPATEL',     'Harshal Patel',          '', 'India', 'Bowler'),
(gen_random_uuid(), 'ISHARMA',    'Ishant Sharma',          '', 'India', 'Bowler'),
(gen_random_uuid(), 'ARSHKHAN',   'Mohd. Arshad Khan',      '', 'India', 'Bowler'),
(gen_random_uuid(), 'KHEJROLIY',  'Kulwant Khejroliya',     '', 'India', 'Bowler'),
(gen_random_uuid(), 'HRANA',      'Harshit Rana',           '', 'India', 'Bowler'),
(gen_random_uuid(), 'DGSINGH',    'Digvesh Singh',          '', 'India', 'Bowler'),
(gen_random_uuid(), 'DEEP',       'Akash Deep',             '', 'India', 'Bowler'),
(gen_random_uuid(), 'UNADKAT',    'Jaydev Unadkat',         '', 'India', 'Bowler'),
(gen_random_uuid(), 'MOSHARMA',   'Mohit Sharma',           '', 'India', 'Bowler'),
(gen_random_uuid(), 'MADHWAL',    'Akash Madhwal',          '', 'India', 'Bowler'),
(gen_random_uuid(), 'KARTIKEYA',  'Kumar Kartikeya',        '', 'India', 'Bowler'),
-- India - All-rounder
(gen_random_uuid(), 'JADEJA',     'Ravindra Jadeja',        '', 'India', 'All-rounder'),
(gen_random_uuid(), 'DUBE',       'Shivam Dube',            '', 'India', 'All-rounder'),
(gen_random_uuid(), 'SHANKAR',    'Vijay Shankar',          '', 'India', 'All-rounder'),
(gen_random_uuid(), 'GOPAL',      'Shreyas Gopal',          '', 'India', 'All-rounder'),
(gen_random_uuid(), 'HPANDYA',    'Hardik Pandya',          '', 'India', 'All-rounder'),
(gen_random_uuid(), 'KPANDYA',    'Krunal Pandya',          '', 'India', 'All-rounder'),
(gen_random_uuid(), 'SWSINGH',    'Swapnil Singh',          '', 'India', 'All-rounder'),
(gen_random_uuid(), 'ROY',        'Anukul Roy',             '', 'India', 'All-rounder'),
(gen_random_uuid(), 'RMSINGH',    'Ramandeep Singh',        '', 'India', 'All-rounder'),
(gen_random_uuid(), 'ABSHARMA',   'Abhishek Sharma',        '', 'India', 'All-rounder'),
(gen_random_uuid(), 'HOODA',      'Deepak Hooda',           '', 'India', 'All-rounder'),
(gen_random_uuid(), 'AXPATEL',    'Axar Patel',             '', 'India', 'All-rounder'),
(gen_random_uuid(), 'ASHWIN',     'Ravichandran Ashwin',    '', 'India', 'All-rounder'),
(gen_random_uuid(), 'NIGAM',      'Vipraj Nigam',           '', 'India', 'All-rounder'),
(gen_random_uuid(), 'LOMROR',     'Mahipal Lomror',         '', 'India', 'All-rounder'),
(gen_random_uuid(), 'BRAR',       'Harpreet Brar',          '', 'India', 'All-rounder'),
(gen_random_uuid(), 'NRANA',      'Nitish Rana',            '', 'India', 'All-rounder'),
(gen_random_uuid(), 'MUSHKHAN',   'Musheer Khan',           '', 'India', 'All-rounder'),
(gen_random_uuid(), 'REDDY',      'Nitish Kumar Reddy',     '', 'India', 'All-rounder'),
(gen_random_uuid(), 'TEWATIA',    'Rahul Tewatia',          '', 'India', 'All-rounder'),
(gen_random_uuid(), 'JYADAV',     'Jayant Yadav',           '', 'India', 'All-rounder'),
(gen_random_uuid(), 'STHAKUR',    'Shardul Thakur',         '', 'India', 'All-rounder'),
(gen_random_uuid(), 'SAMAD',      'Abdul Samad',            '', 'India', 'All-rounder'),
(gen_random_uuid(), 'BADONI',     'Ayush Badoni',           '', 'India', 'All-rounder'),
(gen_random_uuid(), 'SBAHMED',    'Shahbaz Ahmed',          '', 'India', 'All-rounder'),
(gen_random_uuid(), 'SUNDAR',     'Washington Sundar',      '', 'India', 'All-rounder'),
(gen_random_uuid(), 'PARAG',      'Riyan Parag',            '', 'India', 'All-rounder'),
-- India - Wicketkeeper-Batsman
(gen_random_uuid(), 'DHONI',      'MS Dhoni',               '', 'India', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'RAWAT',      'Anuj Rawat',             '', 'India', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'MINZ',       'Robin Minz',             '', 'India', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'PANT',       'Rishabh Pant',           '', 'India', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'IKISHAN',    'Ishan Kishan',           '', 'India', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'JSHARMA',    'Jitesh Sharma',          '', 'India', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'KLRAHUL',    'KL Rahul',               '', 'India', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'PBSINGH',    'Prabhsimran Singh',      '', 'India', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'POREL',      'Abhishek Porel',         '', 'India', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'SAMSON',     'Sanju Samson',           '', 'India', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'JUREL',      'Dhruv Jurel',            '', 'India', 'Wicketkeeper-Batsman'),
-- Australia - Batsman
(gen_random_uuid(), 'HEAD',       'Travis Head',            '', 'Australia', 'Batsman'),
(gen_random_uuid(), 'SMITH',      'Steve Smith',            '', 'Australia', 'Batsman'),
(gen_random_uuid(), 'MCGURK',     'Jake Fraser-McGurk',     '', 'Australia', 'Batsman'),
(gen_random_uuid(), 'WARNER',     'David Warner',           '', 'Australia', 'Batsman'),
-- Australia - Bowler
(gen_random_uuid(), 'STARC',      'Mitchell Starc',         '', 'Australia', 'Bowler'),
(gen_random_uuid(), 'SJOHNSON',   'Spencer Johnson',        '', 'Australia', 'Bowler'),
(gen_random_uuid(), 'HAZLEWOOD',  'Josh Hazlewood',         '', 'Australia', 'Bowler'),
(gen_random_uuid(), 'ZAMPA',      'Adam Zampa',             '', 'Australia', 'Bowler'),
(gen_random_uuid(), 'BARTLETT',   'Xavier Bartlett',        '', 'Australia', 'Bowler'),
-- Australia - All-rounder
(gen_random_uuid(), 'STOINIS',    'Marcus Stoinis',         '', 'Australia', 'All-rounder'),
(gen_random_uuid(), 'MARSH',      'Mitchell Marsh',         '', 'Australia', 'All-rounder'),
(gen_random_uuid(), 'CUMMINS',    'Pat Cummins',            '', 'Australia', 'All-rounder'),
(gen_random_uuid(), 'MAXWELL',    'Glenn Maxwell',          '', 'Australia', 'All-rounder'),
(gen_random_uuid(), 'TDAVID',     'Tim David',              '', 'Australia', 'All-rounder'),
(gen_random_uuid(), 'HARDIE',     'Aaron Hardie',           '', 'Australia', 'All-rounder'),
-- Australia - Wicketkeeper-Batsman
(gen_random_uuid(), 'INGLIS',     'Josh Inglis',            '', 'Australia', 'Wicketkeeper-Batsman'),
-- England - Bowler
(gen_random_uuid(), 'RASHID',     'Adil Rashid',            '', 'England', 'Bowler'),
(gen_random_uuid(), 'TOPLEY',     'Reece Topley',           '', 'England', 'Bowler'),
(gen_random_uuid(), 'ARCHER',     'Jofra Archer',           '', 'England', 'Bowler'),
-- England - All-rounder
(gen_random_uuid(), 'OVERTON',    'Jamie Overton',          '', 'England', 'All-rounder'),
(gen_random_uuid(), 'LIVINGSTO',  'Liam Livingstone',       '', 'England', 'All-rounder'),
(gen_random_uuid(), 'BETHELL',    'Jacob Bethell',          '', 'England', 'All-rounder'),
(gen_random_uuid(), 'JACKS',      'Will Jacks',             '', 'England', 'All-rounder'),
(gen_random_uuid(), 'MALI',       'Moeen Ali',              '', 'England', 'All-rounder'),
-- England - Wicketkeeper-Batsman
(gen_random_uuid(), 'BUTTLER',    'Jos Buttler',            '', 'England', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'SALT',       'Phil Salt',              '', 'England', 'Wicketkeeper-Batsman'),
-- South Africa - Batsman
(gen_random_uuid(), 'BREETZKE',   'Matthew Breetzke',       '', 'South Africa', 'Batsman'),
(gen_random_uuid(), 'PLESSIS',    'Faf du Plessis',         '', 'South Africa', 'Batsman'),
(gen_random_uuid(), 'MILLER',     'David Miller',           '', 'South Africa', 'Batsman'),
-- South Africa - Bowler
(gen_random_uuid(), 'RABADA',     'Kagiso Rabada',          '', 'South Africa', 'Bowler'),
(gen_random_uuid(), 'NORTJE',     'Anrich Nortje',          '', 'South Africa', 'Bowler'),
(gen_random_uuid(), 'COETZEE',    'Gerald Coetzee',         '', 'South Africa', 'Bowler'),
(gen_random_uuid(), 'MAPHAKA',    'Kwena Maphaka',          '', 'South Africa', 'Bowler'),
-- South Africa - All-rounder
(gen_random_uuid(), 'JANSEN',     'Marco Jansen',           '', 'South Africa', 'All-rounder'),
(gen_random_uuid(), 'MULDER',     'Wiaan Mulder',           '', 'South Africa', 'All-rounder'),
(gen_random_uuid(), 'MARKRAM',    'Aiden Markram',          '', 'South Africa', 'All-rounder'),
-- South Africa - Wicketkeeper-Batsman
(gen_random_uuid(), 'DEKOCK',     'Quinton de Kock',        '', 'South Africa', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'KLAASEN',    'Heinrich Klaasen',       '', 'South Africa', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'STUBBS',     'Tristan Stubbs',         '', 'South Africa', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'RICKELTON',  'Ryan Rickelton',         '', 'South Africa', 'Wicketkeeper-Batsman'),
(gen_random_uuid(), 'FERREIRA',   'Donovan Ferreira',       '', 'South Africa', 'Wicketkeeper-Batsman'),
-- New Zealand - Batsman
(gen_random_uuid(), 'CONWAY',     'Devon Conway',           '', 'New Zealand', 'Batsman'),
(gen_random_uuid(), 'PHILLIPS',   'Glenn Phillips',         '', 'New Zealand', 'Batsman'),
(gen_random_uuid(), 'WILLIAMSON', 'Kane Williamson',        '', 'New Zealand', 'Batsman'),
-- New Zealand - Bowler
(gen_random_uuid(), 'BOULT',      'Trent Boult',            '', 'New Zealand', 'Bowler'),
(gen_random_uuid(), 'FERGUSON',   'Lockie Ferguson',        '', 'New Zealand', 'Bowler'),
-- New Zealand - All-rounder
(gen_random_uuid(), 'RAVINDRA',   'Rachin Ravindra',        '', 'New Zealand', 'All-rounder'),
(gen_random_uuid(), 'SANTNER',    'Mitchell Santner',       '', 'New Zealand', 'All-rounder'),
(gen_random_uuid(), 'MITCHELL',   'Daryl Mitchell',         '', 'New Zealand', 'All-rounder'),
-- Sri Lanka - Bowler
(gen_random_uuid(), 'PATHIRANA',  'Matheesha Pathirana',    '', 'Sri Lanka', 'Bowler'),
(gen_random_uuid(), 'MALINGA',    'Eshan Malinga',          '', 'Sri Lanka', 'Bowler'),
(gen_random_uuid(), 'THEEKSHANA', 'Maheesh Theekshana',     '', 'Sri Lanka', 'Bowler'),
(gen_random_uuid(), 'THUSHARA',   'Nuwan Thushara',         '', 'Sri Lanka', 'Bowler'),
(gen_random_uuid(), 'MADUSHANKA', 'Dilshan Madushanka',     '', 'Sri Lanka', 'Bowler'),
-- Sri Lanka - All-rounder
(gen_random_uuid(), 'HASARANGA',  'Wanindu Hasaranga',      '', 'Sri Lanka', 'All-rounder'),
(gen_random_uuid(), 'MENDIS',     'Kamindu Mendis',         '', 'Sri Lanka', 'All-rounder'),
-- Afghanistan - Bowler
(gen_random_uuid(), 'AHMAD',      'Noor Ahmad',             '', 'Afghanistan', 'Bowler'),
(gen_random_uuid(), 'RAHMAN',     'Mujeeb-ur-Rahman',       '', 'Afghanistan', 'Bowler'),
(gen_random_uuid(), 'FAROOQI',    'Fazalhaq Farooqi',       '', 'Afghanistan', 'Bowler'),
(gen_random_uuid(), 'HAQ',        'Naveen-ul-Haq',          '', 'Afghanistan', 'Bowler'),
-- Afghanistan - All-rounder
(gen_random_uuid(), 'RASHKHAN',   'Rashid Khan',            '', 'Afghanistan', 'All-rounder'),
(gen_random_uuid(), 'JANAT',      'Karim Janat',            '', 'Afghanistan', 'All-rounder'),
(gen_random_uuid(), 'OMARZAI',    'Azmatullah Omarzai',     '', 'Afghanistan', 'All-rounder'),
-- Afghanistan - Wicketkeeper-Batsman
(gen_random_uuid(), 'GURBAZ',     'Rahmanullah Gurbaz',     '', 'Afghanistan', 'Wicketkeeper-Batsman'),
-- West Indies - Batsman
(gen_random_uuid(), 'RUTHERFORD', 'Sherfane Rutherford',    '', 'West Indies', 'Batsman'),
(gen_random_uuid(), 'POWELL',     'Rovman Powell',          '', 'West Indies', 'Batsman'),
(gen_random_uuid(), 'HETMYER',    'Shimron Hetmyer',        '', 'West Indies', 'Batsman'),
-- West Indies - Bowler
(gen_random_uuid(), 'JOSEPH',     'Shamar Joseph',          '', 'West Indies', 'Bowler'),
-- West Indies - All-rounder
(gen_random_uuid(), 'RUSSELL',    'Andre Russell',          '', 'West Indies', 'All-rounder'),
(gen_random_uuid(), 'NARINE',     'Sunil Narine',           '', 'West Indies', 'All-rounder'),
(gen_random_uuid(), 'SHEPHERD',   'Romario Shepherd',       '', 'West Indies', 'All-rounder'),
-- West Indies - Wicketkeeper-Batsman
(gen_random_uuid(), 'POORAN',     'Nicholas Pooran',        '', 'West Indies', 'Wicketkeeper-Batsman');
